# Generated by Django 5.0.3 on 2024-06-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regionName',
            new_name='name',
        ),
    ]
