# Generated by Django 5.0.3 on 2024-06-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0003_rename_cartquantity_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
