# Generated by Django 5.0.3 on 2024-06-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0004_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
    ]
